name: StrainLab
options:
  bundleIdPrefix: com.strainlab
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"

packages:
  StrainLabKit:
    path: StrainLabKit

targets:
  StrainLab:
    type: application
    platform: iOS
    sources:
      - path: StrainLab
    dependencies:
      - package: StrainLabKit
      - target: StrainLabWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.strainlab.app
        INFOPLIST_FILE: StrainLab/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
    entitlements:
      path: StrainLab/StrainLab.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.security.application-groups:
          - group.com.strainlab.shared
    info:
      path: StrainLab/Info.plist
      properties:
        CFBundleDisplayName: StrainLab
        CFBundleName: StrainLab
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        NSHealthShareUsageDescription: "StrainLab reads your health data to calculate Recovery, Strain, and Sleep scores."
        NSHealthUpdateUsageDescription: "StrainLab saves workout data to help track your activity."
        UIUserInterfaceStyle: Dark

  StrainLabWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: StrainLabWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.strainlab.app.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.9"
    entitlements:
      path: StrainLabWidget/StrainLabWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.strainlab.shared
    info:
      path: StrainLabWidget/Info.plist
      properties:
        CFBundleDisplayName: StrainLab Widget
        CFBundleName: StrainLabWidget
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  StrainLabWatch:
    type: application
    platform: watchOS
    sources:
      - path: StrainLabWatch
    dependencies:
      - package: StrainLabKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.strainlab.app.watchkitapp
        INFOPLIST_FILE: StrainLabWatch/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "4"
    entitlements:
      path: StrainLabWatch/StrainLabWatch.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
    info:
      path: StrainLabWatch/Info.plist
      properties:
        CFBundleDisplayName: StrainLab
        CFBundleName: StrainLabWatch
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSHealthShareUsageDescription: "StrainLab reads your health data to track workouts and heart rate."
        NSHealthUpdateUsageDescription: "StrainLab saves workout data to HealthKit."
        NSMotionUsageDescription: "StrainLab uses motion data to detect activity levels during workouts."
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.strainlab.app

schemes:
  StrainLab:
    build:
      targets:
        StrainLab: all
    run:
      config: Debug
    archive:
      config: Release
  StrainLabWatch:
    build:
      targets:
        StrainLabWatch: all
    run:
      config: Debug
    archive:
      config: Release
