name: StrainLab
options:
  bundleIdPrefix: com.yourteam
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  
packages:
  StrainLabKit:
    path: StrainLabKit

targets:
  StrainLab:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: StrainLab
        excludes:
          - "**/*.md"
    dependencies:
      - package: StrainLabKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourteam.strainlab
        INFOPLIST_FILE: StrainLab/Info.plist
        CODE_SIGN_ENTITLEMENTS: StrainLab/StrainLab.entitlements
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        DEVELOPMENT_TEAM: YOUR_TEAM_ID_HERE
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: "5.9"
    scheme:
      testTargets: []
      gatherCoverageData: false
    
  StrainLabWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: StrainLabWatch
        excludes:
          - "**/*.md"
    dependencies:
      - package: StrainLabKit
      - target: StrainLab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourteam.strainlab.watchkitapp
        INFOPLIST_FILE: StrainLabWatch/Info.plist
        CODE_SIGN_ENTITLEMENTS: StrainLabWatch/StrainLabWatch.entitlements
        DEVELOPMENT_TEAM: YOUR_TEAM_ID_HERE
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: "5.9"
        SKIP_INSTALL: NO
        TARGETED_DEVICE_FAMILY: "4"
    scheme:
      testTargets: []

schemes:
  StrainLab:
    build:
      targets:
        StrainLab: all
        StrainLabWatch: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
